import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Feeds Arena</title>
        <meta name="description" content="Generated by Feeds Arena" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Vercel Trick By <a href="https://www.feedsarena.com">Feeds Arena</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://www.feedsarena.com/songs/hip-hop-musics/" className={styles.card}>
            <h2>Trending Hip-Hop &rarr;</h2>
            <p>Here you can download trending hip-hop and get latest upto date gist.</p>
          </a>

          <a href="https://www.feedsarena.com/mixtapes/" className={styles.card}>
            <h2>Mixtapes and Latest Gists &rarr;</h2>
            <p>Here you can download trending Mixtapes and get latest upto date gist.</p>
          </a>

          <a
            href="https://www.feedsarena.com/movies/"
            className={styles.card}
          >
            <h2>Movie &rarr;</h2>
            <p>Here you can download free Netflix Movies and enjoy while at home.</p>
          </a>

          <a
            href="https://www.feedsarena.com/articles/sport-news/"
            className={styles.card}
          >
            <h2>Sport News &rarr;</h2>
            <p>
              Here you can find showviz sport news and other national and internation news
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
